name: CI/CD Deployment to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure GCP project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/deliveryinventoryservice .

      - name: Push to Google Container Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/deliveryinventoryservice

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy deliveryinventoryservice \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/deliveryinventoryservice \
            --region asia-south1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }},SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }},SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }},SPRING_REDIS_HOST=${{ secrets.SPRING_REDIS_HOST }},SPRING_REDIS_PASSWORD=${{ secrets.SPRING_REDIS_PASSWORD }},FEIGN_CLIENT_ORDER_URL=${{ secrets.FEIGN_CLIENT_ORDER_URL }},ELASTICSEARCH_URL=${{ secrets.ELASTICSEARCH_URL }},ELASTICSEARCH_USERNAME=${{ secrets.ELASTICSEARCH_USERNAME }},ELASTICSEARCH_APIKEY=${{ secrets.ELASTICSEARCH_APIKEY }},AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }},AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }},AWS_REGION=${{ secrets.AWS_REGION }},AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }},KAFKA_BOOTSTRAP_SERVERS=${{ secrets.KAFKA_BOOTSTRAP_SERVERS }},KAFKA_USERNAME=${{ secrets.KAFKA_USERNAME }},KAFKA_PASSWORD=${{ secrets.KAFKA_PASSWORD }},KAFKA_TRUSTSTORE_PASSWORD=${{ secrets.KAFKA_TRUSTSTORE_PASSWORD }},CLOUDINARY_NAME=${{ secrets.CLOUDINARY_NAME }},CLOUDINARY_KEY=${{ secrets.CLOUDINARY_KEY }},CLOUDINARY_SECRET=${{ secrets.CLOUDINARY_SECRET }}
